---
- name: create namespace
  hosts: master
  become: true
  become_user: root
  tasks:
  - name: Create a k8s namespace
    k8s:
      name: testing
      api_version: v1
      kind: Namespace
      state: present

